Resources:
  WothAmplifyApp:
    Type: AWS::Amplify::App
    Properties:
      Name: WothAmplifyApp
      Repository: https://github.com/khang859/woth-toolbox-aws-amplify
      OauthToken: '{{resolve:secretsmanager:woth-github-token:SecretString:woth-github-token}}'
